/**
 * Studio MARS Project Data
 * This file contains the registry of all projects from 2008 to present.
 * status: "work" means "projekt v delu" (in progress)
 */

const projectData = {
    "2026": {
        list: [
            { artist: "Založba Emanuel", desc: "snemanje, mix in mastering projekta", status: "work" },
            { artist: "Kristjan Hočevar", desc: "produkcija, snemanje avtorske pesmi in izdelava videospota", status: "work" },
            { artist: "Filip Jagodič", desc: "audio&video snemanje in obdelava pesmi", status: "work" },
            { artist: "Revije pevskih zborov JSKD", desc: "audio in video snemanje štirih prireditev", status: "work" },
            { artist: "Društvo upokojencev Mirna", desc: "audio in video snemanje ter ozvočevanje prireditve \"Za Mirno z ljubeznijo\"", status: "work" }
        ],
        audio: [],
        videos: ["0Vsvf0fWgEQ"]
    },
    "2025": {
        list: [
            { artist: "Drugi vagon", desc: "snemanje za drugo zgoščenko", status: "work" },
            { artist: "Sara in Iris", desc: "snemanje promo pesmi" },
            { artist: "Roman Opara", desc: "snemanje avtorske pesmi in produkcija videospota" },
            { artist: "Projekt PODARI PESEM", desc: "snemanje namenskih skladb po naročilu", status: "work" },
            { artist: "Damjana in Doris", desc: "snemanje promo pesmi" },
            { artist: "Roman Končar", desc: "snemanje za televizijsko oddajo" },
            { artist: "Za Mirno z ljubeznijo - 43. prireditev", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Filip Jagodič in Barbara Leben", desc: "izdelava avtorske skladbe ter produkcija videospota", status: "work" },
            { artist: "Revije pevskih zborov JSKD", desc: "audio in video snemanje štirih prireditev", status: "work" },
            { artist: "Založba Emanuel", desc: "mix in mastering projekta", status: "work" },
            { artist: "Uroš Ržišnik", desc: "izdelava in produkcija dveh skladb ter izdelava videospota", status: "work" },
            { artist: "Pozdrav Mirne Šentrupertu", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Marjetka Hribernik", desc: "audio in video snemanje skladbe", status: "work" },
            { artist: "Ko se srečata Dolenjska in Francija v pesmi", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Kristjan Hočevar", desc: "izdelava in produkcija dveh pesmi", status: "work" },
            { artist: "Fernando Mejias", desc: "snemanje avtorske pesmi" },
            { artist: "KD Janez Trdina NM", desc: "ozvočevanje prireditve" },
            { artist: "Borko Horvat", desc: "snemanje avtorske pesmi in izdelava videospota" },
            { artist: "Zimzelen Mirna", desc: "audio&video snemanje in ozvočevanje koncerta" },
            { artist: "Maja Marinčič", desc: "video snemanje koncerta" },
            { artist: "MePZ Leo Fortis", desc: "snemanje in ozvočevanje koncerta" }
        ],
        audio: ["himna-nk-trebnje"],
        videos: ["Zr3oZHCCt_o", "P03MxT6H_Xo", "EJYPq4STQ6w", "L439NaJv2as", "YicA3YLwAd0", "NPFZ50YQBRc", "2Y-ZYdAuKdQ"]
    },
    "2024": {
        list: [
            { artist: "Maja Marinčič", desc: "mix in mastering koncerta", status: "work" },
            { artist: "Marjan Brcar", desc: "snemanje priredb", status: "work" },
            { artist: "Duo SASI", desc: "snemanje kitare in orglic", status: "work" },
            { artist: "Oktet Bori", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Dare Acoustic", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Ansambel Suha solza in Pihalni orkester Trebnje", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Revije otroških, mladinskih in odraslih pevskih zborov Trebnje", desc: "snem. audio in video", status: "work" },
            { artist: "MePZ DU Mirna", desc: "snemanje (audio in video) koncerta ob 25. letnici", status: "work" },
            { artist: "Barb band", desc: "snemanje promo pesmi", status: "work" },
            { artist: "Ansambel Od Dn's", desc: "snemanje materiala za izdajo zgoščenke", status: "work" },
            { artist: "Drugi vagon", desc: "snemanje materiala za izdajo zgoščenke", status: "work" },
            { artist: "Dean", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorske pesmi" },
            { artist: "Kristina Žgur", desc: "snemanje operne glasbe" },
            { artist: "MePZ Leo Fortis", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Blaž in Keli", desc: "snemanje cover pesmi" },
            { artist: "Kailash Kokoppelli", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Šmarnogorski kvintet", desc: "snemanje avtorske pesmi" },
            { artist: "CIK CAK kvintet", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Uroš Ržišnik trio", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Soreline", desc: "koncert v cerkvi" },
            { artist: "Navex", desc: "snemanje tečajev za podjetja" },
            { artist: "Ingenium Ensemble", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Meh Express", desc: "snemanje avtorske pesmi", status: "work" }
        ],
        audio: ["stari-mlin", "hit-the-road-jack-live", "ob-kolpi", "ocean"],
        videos: ["4V_AuR5o84s", "Q8PzJWbPHFI", "cp3JzwAER5s", "-Foejkv-Ae0"]
    },
    "2023": {
        list: [
            { artist: "Matej Lebič", desc: "snemanje demo pesmi" },
            { artist: "Navex", desc: "snemanje seminarjev za podjetja" },
            { artist: "Urška Mitrovič", desc: "snemanje pesmi za osnovno šolo" },
            { artist: "MePZ Notranjska", desc: "snemanje za zgoščenko" },
            { artist: "Ingenium Ensemble", desc: "snemanje za zgoščenko" },
            { artist: "Željan Gligora", desc: "snemanje avtorske dalmatinske pesmi" },
            { artist: "Revije otroških, mladinskih in odraslih pevskih zborov Trebnje", desc: "snem. audio in video" },
            { artist: "Andrej Kaferle", desc: "snemanje avtorske pesmi" },
            { artist: "Vokalna skupina Adoramus", desc: "snemanje za zgoščenko" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko in izdaja projekta" },
            { artist: "Klapa Lavanda", desc: "snemanje avtorske pesmi" },
            { artist: "Dare Acoustic", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Drugi vagon", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Ansambel Od d'ns", desc: "snemanje avtorske pesmi" },
            { artist: "Duo Z andahtjo", desc: "snemanje promo audio in video" },
            { artist: "Blaž Bobnar", desc: "kantavtor, snemanje coverja" },
            { artist: "Kristjan Hočevar", desc: "kantavtor, snemanje avtorske pesmi, audio in video produkcija" },
            { artist: "Sandrijel", desc: "snemanje rap pesmi" },
            { artist: "MePZ Leo Fortis", desc: "snemanje promo pesmi za reklamo" },
            { artist: "Nedelcho Nedelchev", desc: "snemanje kitare" },
            { artist: "Kvartet saksofonov Eternum", desc: "snemanje koncerta" },
            { artist: "Založba Emanuel", desc: "snemanje avtorkskih pesmi za zgoščenko" },
            { artist: "Maja Marinčič", desc: "snemanje priredb" },
            { artist: "Andraž Kovačič", desc: "snemanje harmonike" },
            { artist: "Vokalna skupina Soreline", desc: "snemanje koncerta" },
            { artist: "Ženski pevski zbor Zimzelen", desc: "snemanje koncerta audio in video" }
        ],
        audio: ["zdaj-vem", "pain-train"],
        videos: ["sJwyKHxBbGc", "ZoDM7zJEvE0", "vORLuHL3a3s", "VCouAYPAtD0", "Wtb6DTTqesI", "-820IVgxZQw", "RSpqJC5SvJk", "KyI8ZtnqV8I", "UjXeG-sKxq4", "-YQM7neWqco", "J9pJTPhc8BQ"]
    },
    "2022": {
        list: [
            { artist: "Cik Cak kvintet", desc: "snemanje avtorske pesmi" },
            { artist: "Kristina Žgur", desc: "snemanje opernih pesmi" },
            { artist: "AGB band", desc: "snemanje avtorskih pesmi" },
            { artist: "Lovsko pevsko društvo Martin Krpan Bloke", desc: "snemanje za zgoščenko" },
            { artist: "Ingenium Ensemble", desc: "snemanje za zgoščenko" },
            { artist: "Kvartet Pečjaki", desc: "snemanje ljudskih vokalni pesmi" },
            { artist: "GAMMAS band", desc: "snemanje za zgoščenko" },
            { artist: "Barb band", desc: "projekt za vrtec Trebnje" },
            { artist: "Uroš Cokan", desc: "snemanje avtorske pesmi" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko" },
            { artist: "Mia Koritnik", desc: "snemanje demo pesmi" },
            { artist: "Ratko Zekić", desc: "snemanje avtorskih pesmi" },
            { artist: "MePZ Dolenjske Toplice", desc: "snemanje za zgoščenko" },
            { artist: "Schaka kvintet", desc: "trobilni kvintet, snemanje za zgoščenko" },
            { artist: "Janja in Darko Štamcar", desc: "snemanje ljudske pesmi" },
            { artist: "Hišni ansambel Avsenik", desc: "snemanje za Renatov 80. rojstni dan" },
            { artist: "Meh Express", desc: "snemanje avtorske pesmi" },
            { artist: "Kvartet Ethernum", desc: "snemanje koncerta, KD Mirna" },
            { artist: "Vivi Vah", desc: "snemanje avtorskih pesmi" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorske pesmi" },
            { artist: "The Balkan Experience of Song and Ritual", desc: "snemanje avtorskih pesmi" },
            { artist: "Družina Gostiša", desc: "snemanje za zgoščenko" },
            { artist: "Dare Acoustic", desc: "snemanje demo posnetkov" }
        ],
        audio: ["jezicek", "v-hribih-se-dela-dan"],
        videos: ["Cc6rkpOcj6g", "JyoJ5eY7qjI", "ngobW3S_-bE"]
    },
    "2021": {
        list: [
            { artist: "Borko Horvat", desc: "snemanje avtorske pesmi" },
            { artist: "Dean Černec", desc: "snemanje avtorske pesmi" },
            { artist: "Drugi vagon & AGB band", desc: "snemanje avtorskih pesmi" },
            { artist: "Vitja Zlatnar", desc: "rap, snemanje demo posnetkov", status: "work" },
            { artist: "Blaž Jeršin", desc: "rap, snemanje demo posnetkov", status: "work" },
            { artist: "Kailash Kokoppelli", desc: "snemanje avtorskih pesmi" },
            { artist: "Jan Grčar & Janja Podgrajšek", desc: "snemanje narodnozabavnih posnetkov" },
            { artist: "Matej Glivar & Anja", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "OŠ Šentrupert & Barbara Leben", desc: "projekt za glasbeno šolo na daljavo" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko" },
            { artist: "Aljoša Deferri & Mojca Dolenc", desc: "snemanje krajevne himne" },
            { artist: "Schaka kvintet", desc: "trobilni kvintet, snemanje za zgoščenko" },
            { artist: "Klapa Lavanda", desc: "snemanje za zgoščenko" },
            { artist: "Vivi Vah", desc: "snemanje avtorskih pesmi" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorskih pesmi" }
        ],
        audio: ["peski-oktet"],
        videos: ["-A1YMNx8qSc", "kVzvCfzGoX4"]
    },
    "2020": {
        list: [
            { artist: "Cik-cak kvintet", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Ansambel Suha solza", desc: "mastering in izdaja zgoščenke" },
            { artist: "Filip Jagodič", desc: "snemanje in izdaja tretje zgoščenke" },
            { artist: "Ingenium Ensemble", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Zidaniški kvintet", desc: "mastering in izdaja zgoščenke" },
            { artist: "Maja Mlakar", desc: "kantavtorica, izdaja zgoščenke" },
            { artist: "Glasbena šola Aleš Smolič", desc: "snemanje audio in video" },
            { artist: "Lovski pevski zbor Matin Krpan Bloke", desc: "snemanje in izdaja zgoščenke" },
            { artist: "Ratko Zekić", desc: "violončelo, snemanje demo pesmi", status: "work" },
            { artist: "Kvartet Strmole", desc: "snemanje pesmi za zgoščenko", status: "work" },
            { artist: "Urška Mitrovič", desc: "snemanje avtorske pesmi" },
            { artist: "Uroš Ržišnik", desc: "snemanje vokalov za avtorsko pesem" }
        ],
        audio: ["mati-domovina", "sijaj-mi-soncece"],
        videos: ["wrgC8VeRFPM", "KPP-UOhs8iE", "DQUbrlZj1sQ", "n1WgZTvZTcM"]
    },
    "2019": {
        list: [
            { artist: "Drugi vagon & Dare Acoustic", desc: "snemanje za zgoščenko" },
            { artist: "Ljudski pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Laura Marn", desc: "snemanje demo pesmi" },
            { artist: "Vrtec Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Maja Mlakar", desc: "kantavtorica, snemanje za zgoščenko", status: "work" },
            { artist: "Ratko Zekić", desc: "violončelo, snemanje za zgoščenko", status: "work" },
            { artist: "Revije otroških in odraslih pevski skupin v občini Trebnje", desc: "snemanje na terenu" },
            { artist: "Dean Černec", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Bojan Rus", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Moški pevski zbor Tabor Cerknica", desc: "snemanje za zgoščenko" },
            { artist: "Ansambel Suha solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "AGB band", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Zidaniški kvintet", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Marjan Rogelj", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Mešani zbor upokojencev Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Trebanjski oktet", desc: "snemanje za zgoščenko" },
            { artist: "MPZ Mirna s filharmoniki RTV Slovenija", desc: "snemanje božičnega koncerta" },
            { artist: "Željko Rokvič z bandom", desc: "snemanje za zgoščenko" },
            { artist: "Sara Jagrič", desc: "snemanje demo pesmi" },
            { artist: "Vladimir", desc: "opera, snemanje demo pesmi" }
        ],
        audio: ["resta-immobile", "fly-me-the-moon", "frozen"],
        videos: ["eQHiP9a6WD0", "b6XDgs8TN0A"]
    },
    "2018": {
        list: [
            { artist: "Jan Nograšek", desc: "snemanje avtorske pesmi" },
            { artist: "Jan Pance", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "Liljana Pance", desc: "snemanje opernih arij" },
            { artist: "Luka Žitnik trio", desc: "snemanje narodnozabavne skladbe" },
            { artist: "Filip Jagodič", desc: "snemanje za zgoščenko" },
            { artist: "Ah te orglice", desc: "snemanje srečanja orgličarjev v Mokronogu" },
            { artist: "Pevski zbor OŠ Veliki Gaber", desc: "snemanje šolske himne" },
            { artist: "Bojan Rus", desc: "snemanje avtorske pesmi" },
            { artist: "Revije otroških in odraslih pevski skupin v občini Trebnje", desc: "snemanje na terenu" },
            { artist: "Skupina Soreline", desc: "snemanje koncerta" },
            { artist: "Storm Born Studio Italia", desc: "snemanje reklame za računalniško igro" },
            { artist: "Slavko Podboj", desc: "snemanje teksta za otvoritev muzeja Lojzeta Slaka" },
            { artist: "Ljudski pevci in godci Trebelno", desc: "snemanje za zgoščenko" },
            { artist: "Ljudski pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Mešani zbor upokojencev Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Metro Audio Video Studio", desc: "snemanje voiceover seminarjev za slovenska podjetja" },
            { artist: "Za Mirno z ljubeznijo", desc: "snemanje opernega koncerta (Irena Yebuah Tiran ...)" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta" },
            { artist: "Manca Pirc", desc: "snemanje demo posnetkov" }
        ],
        audio: ["killing-me-softly"],
        videos: ["e6mq6FEuepI"]
    },
    "2017": {
        list: [
            { artist: "Zagriški fantje", desc: "snemanje za zgoščenko" },
            { artist: "Alen Vogrinec vesel & Zidaniški kvintet", desc: "snemanje demo pesmi" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta" },
            { artist: "Ema Lavrič & Laura Marn", desc: "snemanje demo pesmi" },
            { artist: "Ernest Klenovšek in Miran Klenovšek", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Drugi vagon", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "18. mednarodni festival ustnih harmonik 2017", desc: "snemanje na terenu" },
            { artist: "Občočna revija odraslih pevskih zborov Mokronog - Trebelno", desc: "snemanje na terenu" },
            { artist: "Ana Vrtačnik", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "Andrej Grandovec band in Rudarski oktet", desc: "snemanje dalmatinske pesmi", status: "work" },
            { artist: "Ansambel Suha Solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Glasbena skupina 5K", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Jerica Steklasa", desc: "snemanje koncerta" },
            { artist: "Ingenium Ensemble (Strmole kvartet)", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Maja Mlakar", desc: "kantavtorica, kitara, snemanje demo pesmi", status: "work" },
            { artist: "Sara Zajc", desc: "klasična kitara, snemanje za zgoščenko", status: "work" },
            { artist: "Darja Štamcar", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Hišni ansambel Avsenik", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Matej Pekolj", desc: "snemanje demo pesmi za harmoniko", status: "work" },
            { artist: "Željko Rokvič band", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje koncerta", status: "work" }
        ],
        audio: [],
        videos: []
    },
    "2016": {
        list: [
            { artist: "Darja Štamcar", desc: "demo posnetki" },
            { artist: "Fantje iz praprotna & družba", desc: "snemanje priložnostne pesmi za praznovanje abrahama" },
            { artist: "Ansambel Suha Solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Studio Virc", desc: "snemanje za telefonsko tajnico" },
            { artist: "Miran Černec", desc: "kantavtor, demo posnetki", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje koncerta ob 35 letnici" },
            { artist: "Timo Grandovec & Sinovi cvička", desc: "snemanje demo pesmi" },
            { artist: "Vizija računovodstvo", desc: "snemanje radijske reklame" },
            { artist: "Občinski pihalni orkester Trebnje", desc: "snemanje za zgoščenko ob 90 letnici" },
            { artist: "MePZ Notranjska", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Oriflame", desc: "snemanje za podjetje Oriflame kozmetika d.o.o." },
            { artist: "Ansambel M-Tom Mirna", desc: "snemanje posnetka za promocijo podjetja M-Tom" },
            { artist: "Luka Groboljšek & Zagorski oktet", desc: "snemanje pesmi za promo občine Zagorje" },
            { artist: "Manca Pirc", desc: "demo posnetki" },
            { artist: "Danilo Lukan", desc: "demo posnetki" },
            { artist: "OŠ Šentrupert", desc: "snemanje za himno" },
            { artist: "Ansambel Mladi Dolenjci", desc: "snemanje za reklamo" },
            { artist: "AGB in prijatelji", desc: "snemanje dalmatinske pesmi" },
            { artist: "Tinkara Lazar", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Matevž Mikeln", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Tilen Zakrajšek", desc: "bobni, snemanje demo posnetkov", status: "work" }
        ],
        audio: [],
        videos: []
    },
    "2015": {
        list: [
            { artist: "Trio adijo", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Željko Mevželj", desc: "demo posnetki" },
            { artist: "Luka Groboljšek", desc: "demo posnetki" },
            { artist: "Ansambel Vrisk", desc: "snemanje za zgoščenko" },
            { artist: "Pihalni orkester Trebnje", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Za Mirno z ljubeznijo", desc: "snemanje koncerta in izdelava zgoščenk" },
            { artist: "Ratko", desc: "violončelo, demo posnetki" },
            { artist: "Matevž Mikeln", desc: "avtorska glasba, snemanje za zgoščenko", status: "work" },
            { artist: "Pevski zbor slepih in slabovidnih Novo Mesto", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "DMT Hardcore", desc: "mastering" },
            { artist: "Dean Černec", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Lucija Tacer", desc: "demo posnetki" },
            { artist: "MePZ Matija Tomc Mirna", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Srečanje ZDUS Cankarjev dom", desc: "snemanje preireditve in izdaja zgoščenke", status: "work" },
            { artist: "Sara Zajc", desc: "akustična kitara, demo posnetki", status: "work" },
            { artist: "Žan ograjšek", desc: "kantavtor, demo posnetki", status: "work" },
            { artist: "Koncert oktet Lipa", desc: "snemanje koncerta", status: "work" },
            { artist: "Vokalna skupina Črta", desc: "demo posnetki", status: "work" },
            { artist: "Tinkara Lazar", desc: "demo posnetki", status: "work" },
            { artist: "Studio Virc", desc: "snemanje telefonske tajnice za T2" },
            { artist: "Metro Audio VIdeo", desc: "snemanje slovenske različice za iROBOT" }
        ],
        audio: [],
        videos: []
    },
    "2014": {
        list: [
            { artist: "Skupina JAMM", desc: "snemanje demo posnetkov" },
            { artist: "Ansambel Suha solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Studio Virc", desc: "snemanje za video produkcijo" },
            { artist: "Skupina Dežur", desc: "snemanje pesmi za slovensko popevko 2014" },
            { artist: "Primož Bulc", desc: "kantavtor, snemanje za zgoščenko" },
            { artist: "Tinkara Lazar", desc: "snemanje demo posnetkov" },
            { artist: "Godalni orkester glasbene šole Trebnje z Bernardo Fink", desc: "koncert" },
            { artist: "MePZ DU Mirna", desc: "snemanje koncerta ob 15. letnici" },
            { artist: "Ansambel \"Tom Mirna\"", desc: "snemanje demo posnetkov" },
            { artist: "Ansambel Kolibri", desc: "snemanje demo posnetkov" },
            { artist: "Pevski zbor Tabor Cerknica", desc: "snemanje za zgoščenko" },
            { artist: "Vokalni kvartet Slavček", desc: "snemanje za zgoščenko" },
            { artist: "No Name band", desc: "demo posnetki" },
            { artist: "Zveza društva upokojencev Slovenije", desc: "snemanje srečanja, Cankarjev dom" },
            { artist: "Matej Glivar", desc: "demo posnetki" },
            { artist: "Krishna", desc: "akustična kitara, demo posnetki" },
            { artist: "Vaški pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Ernest Klenovšek", desc: "harmonika, snemanje za zgoščenko" },
            { artist: "Grajski oktet", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Matjaž Zupančič", desc: "snemanje klavirja, demo posnetki" }
        ],
        audio: [],
        videos: []
    },
    "2013": {
        list: [
            { artist: "Zlobko Big Band in revijski orkester", desc: "sneman. himne 20 let mesta Trebnje" },
            { artist: "Ivo Carič", desc: "klasična kitara, posnetki za zgoščenko" },
            { artist: "Ansambel Suha solza", desc: "material za zgoščenko", status: "work" },
            { artist: "Daša Savić", desc: "violina, demo posnetki" },
            { artist: "Sistem ena d.o.o", desc: "snemanje za telefonsko tajnico" },
            { artist: "Tinkara Lazar", desc: "demo posnetki" },
            { artist: "TMC", desc: "rap, demo posnetki" },
            { artist: "Skupina DeŽur", desc: "demo posnetek" },
            { artist: "Glasbena šola Studio Kreator", desc: "za zgoščenko ljudskih pesmi" },
            { artist: "Glasbena šola Marolt", desc: "snemanje za promocijsko pesem" },
            { artist: "Ana Zlobko", desc: "violončelo, koncert" },
            { artist: "Ansambel Dolinarji", desc: "narodno-zabavna, demo posnetek" },
            { artist: "MePZ društva upokojencev Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Irena Tratnik in Blaž Jurjevčič", desc: "snemanje za zgoščenko" },
            { artist: "Žan Ograjšek", desc: "kantavtor, demo posnetki" },
            { artist: "Mladi godci", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Metro Audio & Video", desc: "snemanje materiala za aplikacijo za navigacijo" },
            { artist: "Sandra Erpe", desc: "snemanje avtorskega singla" },
            { artist: "Dejan Černec", desc: "kantavtor (s triom Blaž Jurjevčič, Vlado Pirc, Bogdan Turnšek)" },
            { artist: "Vokalna skupina Rozalije", desc: "demo posnetki" },
            { artist: "Damjan Plevnik", desc: "demo posnetki" },
            { artist: "Zimazakon band", desc: "demo posnetki" },
            { artist: "MePZ društva upokojencev Mirna", desc: "snemanje in izdaja koncerta Cankarjev dom" },
            { artist: "Klavdija Zakrajšek", desc: "snemanje demo posnetka" },
            { artist: "Srečanje oktetov Dolenjske in Bele krajine 2013", desc: "snemanje koncerta" },
            { artist: "Julija Omahen", desc: "snemanje demo posnetka" },
            { artist: "KUD Matija Tomc Mirna", desc: "snemanje za zgoščenko" }
        ],
        audio: [],
        videos: []
    },
    "2012": {
        list: [
            { artist: "Dekliška skupina SANDBARRY", desc: "produkcija in snemanje" },
            { artist: "Tinkara Lazar", desc: "demo posnetki" },
            { artist: "Ženski zbor Zimzelen Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Asnambel Vrisk", desc: "snemanje za videospot" },
            { artist: "Glasbena šola Marolt", desc: "snemanje mladih harmonikašev" },
            { artist: "Eva Virc", desc: "produkcija, aranžiranje in snemanje avtorske pesmi" },
            { artist: "OŠ Trebnje", desc: "snemanje pevskih skupin za zgoščenko" },
            { artist: "Ansambel Ponos", desc: "demo posnetki" },
            { artist: "Ansambel Ravbar", desc: "demo posnetki" },
            { artist: "Ansambel Posluh", desc: "demo posnetki" },
            { artist: "Pihalni orkester Trebnje", desc: "snemanje koncerta filmske glasbe" },
            { artist: "Dean Černec", desc: "kantavtor, demo posnetki" },
            { artist: "Skupina Vaški pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Glasbena šola Studio Kreator", desc: "snemanje materiala za učenje na daljavo" },
            { artist: "Tjaša Boršnak", desc: "demo posnetek" },
            { artist: "Studio Virc d.o.o", desc: "snemanje zvočne podlage za video" },
            { artist: "Ernest Klenovšek", desc: "harmonika, snemanje za zgoščenko" },
            { artist: "Ansambel Glivar", desc: "demo posnetki" },
            { artist: "MEPZ Mirna in orkester Slovenske filharmonije", desc: "koncert" }
        ],
        audio: [],
        videos: []
    },
    "2011": {
        list: [
            { artist: "HDLab", desc: "hardcore, mastering za cd" },
            { artist: "Anica Blažič", desc: "snemanje za oddajo Slovenija ima talent 2011" },
            { artist: "Obrtniški pevski zbor Notranjska", desc: "snemanje materiala za zgoščenko" },
            { artist: "Slavko Podboj", desc: "snemanje radijskih reklam" },
            { artist: "Biizy", desc: "rap, demo posnetki" },
            { artist: "Klapa Kres", desc: "posnetek za tekmovanje dalmatinskih klap Korčula 2011", status: "work" },
            { artist: "Špela Smuk", desc: "snemanje reklam za županske volitve" },
            { artist: "Oto Pestner in Zidaniški kvintet", desc: "projekt avtorja A. Krkoviča" },
            { artist: "Vrtec Trebnje", desc: "demo posnetki" },
            { artist: "MePZ Anton Foerster, Marcos Fink", desc: "proj. za oblet. plebiscita" },
            { artist: "Marko Kuzhnik", desc: "rap, demo posnetki" },
            { artist: "Klavdija Zakrajšek", desc: "demo posnetki" },
            { artist: "Kvartet Sever", desc: "vokalna zasedba, material za zgoščenko" },
            { artist: "Katja Stropnik", desc: "demo posnetki" },
            { artist: "Ansambel Suha solza", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Pihalni orkester Botriček", desc: "snemanje priložnostne zasedbe" }
        ],
        audio: [],
        videos: []
    },
    "2010": {
        list: [
            { artist: "Andrej Mežan, Studio MARS", desc: "In the Sweet (Acappella)" },
            { artist: "Mešani pevski zbor Kres Čatež", desc: "material za zgoščenko" },
            { artist: "Trebanjski oktet", desc: "material za zgoščenko ob 30 letnici" },
            { artist: "The Call Boys", desc: "demo posnetki" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta ob 20 letnici" },
            { artist: "Albin Slabe, godec ljudskih viž", desc: "material za zgočenko" },
            { artist: "Folklorna skupina Nasmeh", desc: "material za zgoščenko" },
            { artist: "Godalni trio Viva", desc: "material za zgoščenko" },
            { artist: "Glasbena šola Studio Kreator", desc: "material za gl. šolo na daljavo" }
        ],
        audio: [],
        videos: []
    },
    "2009": {
        list: [
            { artist: "Limited Squad (LSQ)", desc: "rap, demo posnetki" },
            { artist: "Schlager kvintet", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Marko Kuzhnik", desc: "rap, demo posnetki" },
            { artist: "Trenotek kvartet", desc: "ljudske pesmi, material za zgoščenko" },
            { artist: "Ansambel Vrisk", desc: "narodno-zabavna, material za zgoščenko" },
            { artist: "Triglavski muzikanti", desc: "material za zgoščenko" },
            { artist: "Zidaniški kvintet", desc: "material za zgoščenko" },
            { artist: "Otroški zborček VVZ Trebnje", desc: "demo posnetki" },
            { artist: "Glasbena skupina Stopinje", desc: "demo posnetki" },
            { artist: "MePZ Danica", desc: "material za zgoščenko" },
            { artist: "Kvartet tub, člani orkestra Slovenske vojske", desc: "demo posnetki" },
            { artist: "Gianni Rijavec in Zidaniški kvintet", desc: "skupen projekt" },
            { artist: "Vokalna skupina Ragle", desc: "material za zgoščenko" }
        ],
        audio: [],
        videos: []
    },
    "2008": {
        list: [
            { artist: "Zlobko Big Band z Nušo Derendo in Rajkom Vavpetičem", desc: "demo posnetki" },
            { artist: "Stil Quartet", desc: "demo posnetki, producent Oto Pestner" },
            { artist: "Oto Pestner", desc: "za zgoščenko \"Tribute to Golden Gate Quartet\"" },
            { artist: "Marjetka Hribernik", desc: "violončelo, demo posnetki, producent Oto Pestner" },
            { artist: "Matej Krajnc", desc: "kantavtor, material za zgoščenko" },
            { artist: "Trebanjski oktet", desc: "demo posnetki" },
            { artist: "Zidaniški kvintet", desc: "demo posnetki" },
            { artist: "D'Neeb", desc: "rock, material za zgoščenko" }
        ],
        audio: [],
        videos: []
    }
};
