/**
 * Studio MARS Project Data
 * This file contains the registry of all projects from 2008 to present.
 * status: "work" means "projekt v delu" (in progress)
 */

const projectData = {
    "2026": {
        list: [
            { artist: "Založba Emanuel", desc: "snemanje, mix in mastering projekta", status: "work" },
            { artist: "Kristjan Hočevar", desc: "produkcija, snemanje avtorske pesmi in izdelava videospota", status: "work" },
            { artist: "Filip Jagodič", desc: "audio&video snemanje in obdelava pesmi", status: "work" },
            { artist: "Revije pevskih zborov JSKD", desc: "audio in video snemanje štirih prireditev", status: "work" },
            { artist: "Društvo upokojencev Mirna", desc: "audio in video snemanje ter ozvočevanje prireditve \"Za Mirno z ljubeznijo\"", status: "work" },
            { artist: "Drugi vagon", desc: "ozvočevanje in snemanje koncerta *" },
            { artist: "Erazem Žganjar", desc: "ozvočevanje in snemanje koncerta *" }
        ],
        audio: [],
        videos: ["0Vsvf0fWgEQ"]
    },
    "2025": {
        list: [
            { artist: "Drugi vagon", desc: "snemanje za drugo zgoščenko", status: "work" },
            { artist: "Sara in Iris", desc: "snemanje promo pesmi" },
            { artist: "Roman Opara", desc: "snemanje avtorske pesmi and produkcija videospota" },
            { artist: "Projekt PODARI PESEM", desc: "snemanje namenskih skladb po naročilu", status: "work" },
            { artist: "Damjana in Doris", desc: "snemanje promo pesmi" },
            { artist: "Roman Končar", desc: "snemanje za televizijsko oddajo" },
            { artist: "Za Mirno z ljubeznijo - 43. prireditev", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Filip Jagodič in Barbara Leben", desc: "izdelava avtorske skladbe ter produkcija videospota", status: "work" },
            { artist: "Revije pevskih zborov JSKD", desc: "audio in video snemanje štirih prireditev", status: "work" },
            { artist: "Založba Emanuel", desc: "mix in mastering projekta", status: "work" },
            { artist: "Uroš Ržišnik", desc: "izdelava in produkcija dveh skladb ter izdelava videospota", status: "work" },
            { artist: "Pozdrav Mirne Šentrupertu", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Marjetka Hribernik", desc: "audio in video snemanje skladbe", status: "work" },
            { artist: "Ko se srečata Dolenjska in Francija v pesmi", desc: "audio in video snemanje koncerta", status: "work" },
            { artist: "Kristjan Hočevar", desc: "izdelava in produkcija dveh pesmi", status: "work" },
            { artist: "Fernando Mejias", desc: "snemanje avtorske pesmi" },
            { artist: "KD Janez Trdina NM", desc: "ozvočevanje prireditve" },
            { artist: "Borko Horvat", desc: "snemanje avtorske pesmi in izdelava videospota" },
            { artist: "Zimzelen Mirna", desc: "audio&video snemanje in ozvočevanje koncerta" },
            { artist: "Maja Marinčič", desc: "video snemanje koncerta" },
            { artist: "MePZ Leo Fortis", desc: "snemanje in ozvočevanje koncerta" }
        ],
        audio: ["studiomars31/himna-nk-trebnje"],
        videos: ["Zr3oZHCCt_o", "P03MxT6H_Xo", "EJYPq4STQ6w", "L439NaJv2as", "YicA3YLwAd0", "NPFZ50YQBRc", "2Y-ZYdAuKdQ"]
    },
    "2024": {
        list: [
            { artist: "Maja Marinčič", desc: "mix in mastering koncerta", status: "work" },
            { artist: "Marjan Brcar", desc: "snemanje priredb", status: "work" },
            { artist: "Duo SASI", desc: "snemanje kitare in orglic", status: "work" },
            { artist: "Oktet Bori", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Dare Acoustic", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Ansambel Suha solza in Pihalni orkester Trebnje", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Revije otroških, mladinskih in odraslih pevskih zborov Trebnje", desc: "snem. audio in video", status: "work" },
            { artist: "MePZ DU Mirna", desc: "snemanje (audio in video) koncerta ob 25. letnici", status: "work" },
            { artist: "Barb band", desc: "snemanje promo pesmi", status: "work" },
            { artist: "Ansambel Od Dn's", desc: "snemanje materiala za izdajo zgoščenke", status: "work" },
            { artist: "Drugi vagon", desc: "snemanje materiala za izdajo zgoščenke", status: "work" },
            { artist: "Dean", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorske pesmi" },
            { artist: "Kristina Žgur", desc: "snemanje operne glasbe" },
            { artist: "MePZ Leo Fortis", desc: "snemanje avtorskih pesmi", status: "work" },
            { artist: "Blaž in Keli", desc: "snemanje cover pesmi" },
            { artist: "Kailash Kokoppelli", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Šmarnogorski kvintet", desc: "snemanje avtorske pesmi" },
            { artist: "CIK CAK kvintet", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Uroš Ržišnik trio", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Soreline", desc: "koncert v cerkvi" },
            { artist: "Navex", desc: "snemanje tečajev za podjetja" },
            { artist: "Ingenium Ensemble", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Meh Express", desc: "snemanje avtorske pesmi", status: "work" }
        ],
        audio: ["studiomars31/stari-mlin", "studiomars31/hit-the-road-jack-live", "studiomars31/ob-kolpi", "studiomars31/ocean"],
        videos: ["4V_AuR5o84s", "Q8PzJWbPHFI", "cp3JzwAER5s", "-Foejkv-Ae0"]
    },
    "2023": {
        list: [
            { artist: "Matej Lebič", desc: "snemanje demo pesmi" },
            { artist: "Navex", desc: "snemanje seminarjev za podjetja" },
            { artist: "Urška Mitrovič", desc: "snemanje pesmi za osnovno šolo" },
            { artist: "MePZ Notranjska", desc: "snemanje za zgoščenko" },
            { artist: "Ingenium Ensemble", desc: "snemanje za zgoščenko" },
            { artist: "Željan Gligora", desc: "snemanje avtorske dalmatinske pesmi" },
            { artist: "Revije otroških, mladinskih in odraslih pevskih zborov Trebnje", desc: "snem. audio in video" },
            { artist: "Andrej Kaferle", desc: "snemanje avtorske pesmi" },
            { artist: "Vokalna skupina Adoramus", desc: "snemanje za zgoščenko" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko in izdaja projekta" },
            { artist: "Klapa Lavanda", desc: "snemanje avtorske pesmi" },
            { artist: "Dare Acoustic", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Drugi vagon", desc: "snemanje avtorske pesmi", status: "work" },
            { artist: "Ansambel Od d'ns", desc: "snemanje avtorske pesmi" },
            { artist: "Duo Z andahtjo", desc: "snemanje promo audio in video" },
            { artist: "Blaž Bobnar", desc: "kantavtor, snemanje coverja" },
            { artist: "Kristjan Hočevar", desc: "kantavtor, snemanje avtorske pesmi, audio in video produkcija" },
            { artist: "Sandrijel", desc: "snemanje rap pesmi" },
            { artist: "MePZ Leo Fortis", desc: "snemanje promo pesmi za reklamo" },
            { artist: "Nedelcho Nedelchev", desc: "snemanje kitare" },
            { artist: "Kvartet saksofonov Eternum", desc: "snemanje koncerta" },
            { artist: "Založba Emanuel", desc: "snemanje avtorkskih pesmi za zgoščenko" },
            { artist: "Maja Marinčič", desc: "snemanje priredb" },
            { artist: "Andraž Kovačič", desc: "snemanje harmonike" },
            { artist: "Vokalna skupina Soreline", desc: "snemanje koncerta" },
            { artist: "Ženski pevski zbor Zimzelen", desc: "snemanje koncerta audio in video" }
        ],
        audio: ["studiomars31/zdaj-vem", "studiomars31/pain-train"],
        videos: ["sJwyKHxBbGc", "ZoDM7zJEvE0", "vORLuHL3a3s", "VCouAYPAtD0", "Wtb6DTTqesI", "-820IVgxZQw", "RSpqJC5SvJk", "KyI8ZtnqV8I", "UjXeG-sKxq4", "-YQM7neWqco", "J9pJTPhc8BQ"]
    },
    "2022": {
        list: [
            { artist: "Cik Cak kvintet", desc: "snemanje avtorske pesmi" },
            { artist: "Kristina Žgur", desc: "snemanje opernih pesmi" },
            { artist: "AGB band", desc: "snemanje avtorskih pesmi" },
            { artist: "Lovsko pevsko društvo Martin Krpan Bloke", desc: "snemanje za zgoščenko" },
            { artist: "Ingenium Ensemble", desc: "snemanje za zgoščenko" },
            { artist: "Kvartet Pečjaki", desc: "snemanje ljudskih vokalni pesmi" },
            { artist: "GAMMAS band", desc: "snemanje za zgoščenko" },
            { artist: "Barb band", desc: "projekt za vrtec Trebnje" },
            { artist: "Uroš Cokan", desc: "snemanje avtorske pesmi" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko" },
            { artist: "Mia Koritnik", desc: "snemanje demo pesmi" },
            { artist: "Ratko Zekić", desc: "snemanje avtorskih pesmi" },
            { artist: "MePZ Dolenjske Toplice", desc: "snemanje za zgoščenko" },
            { artist: "Schaka kvintet", desc: "trobilni kvintet, snemanje za zgoščenko" },
            { artist: "Janja in Darko Štamcar", desc: "snemanje ljudske pesmi" },
            { artist: "Hišni ansambel Avsenik", desc: "snemanje za Renatov 80. rojstni dan" },
            { artist: "Meh Express", desc: "snemanje avtorske pesmi" },
            { artist: "Kvartet Ethernum", desc: "snemanje koncerta, KD Mirna" },
            { artist: "Vivi Vah", desc: "snemanje avtorskih pesmi" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorske pesmi" },
            { artist: "The Balkan Experience of Song and Ritual", desc: "snemanje avtorskih pesmi" },
            { artist: "Družina Gostiša", desc: "snemanje za zgoščenko" },
            { artist: "Dare Acoustic", desc: "snemanje demo posnetkov" }
        ],
        audio: ["studiomars31/jezicek", "studiomars31/v-hribih-se-dela-dan"],
        videos: ["Cc6rkpOcj6g", "JyoJ5eY7qjI", "ngobW3S_-bE"]
    },
    "2021": {
        list: [
            { artist: "Borko Horvat", desc: "snemanje avtorske pesmi" },
            { artist: "Dean Černec", desc: "snemanje avtorske pesmi" },
            { artist: "Drugi vagon & AGB band", desc: "snemanje avtorskih pesmi" },
            { artist: "Vitja Zlatnar", desc: "rap, snemanje demo posnetkov", status: "work" },
            { artist: "Blaž Jeršin", desc: "rap, snemanje demo posnetkov", status: "work" },
            { artist: "Kailash Kokoppelli", desc: "snemanje avtorskih pesmi" },
            { artist: "Jan Grčar & Janja Podgrajšek", desc: "snemanje narodnozabavnih posnetkov" },
            { artist: "Matej Glivar & Anja", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "OŠ Šentrupert & Barbara Leben", desc: "projekt za glasbeno šolo na daljavo" },
            { artist: "Peški oktet", desc: "snemanje za zgoščenko" },
            { artist: "Aljoša Deferri & Mojca Dolenc", desc: "snemanje krajevne himne" },
            { artist: "Schaka kvintet", desc: "trobilni kvintet, snemanje za zgoščenko" },
            { artist: "Klapa Lavanda", desc: "snemanje za zgoščenko" },
            { artist: "Vivi Vah", desc: "snemanje avtorskih pesmi" },
            { artist: "Ema Suhadolnik", desc: "snemanje avtorskih pesmi" }
        ],
        audio: ["studiomars31/peski-oktet"],
        videos: ["-A1YMNx8qSc", "kVzvCfzGoX4"]
    },
    "2020": {
        list: [
            { artist: "Cik-cak kvintet", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Ansambel Suha solza", desc: "mastering in izdaja zgoščenke" },
            { artist: "Filip Jagodič", desc: "snemanje in izdaja tretje zgoščenke" },
            { artist: "Ingenium Ensemble", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Zidaniški kvintet", desc: "mastering in izdaja zgoščenke" },
            { artist: "Maja Mlakar", desc: "kantavtorica, izdaja zgoščenke" },
            { artist: "Glasbena šola Aleš Smolič", desc: "snemanje audio in video" },
            { artist: "Lovski pevski zbor Matin Krpan Bloke", desc: "snemanje in izdaja zgoščenke" },
            { artist: "Ratko Zekić", desc: "violončelo, snemanje demo pesmi", status: "work" },
            { artist: "Kvartet Strmole", desc: "snemanje pesmi za zgoščenko", status: "work" },
            { artist: "Urška Mitrovič", desc: "snemanje avtorske pesmi" },
            { artist: "Uroš Ržišnik", desc: "snemanje vokalov za avtorsko pesem" }
        ],
        audio: ["studiomars31/mati-domovina", "studiomars31/sijaj-mi-soncece"],
        videos: ["wrgC8VeRFPM", "KPP-UOhs8iE", "DQUbrlZj1sQ", "n1WgZTvZTcM"]
    },
    "2019": {
        list: [
            { artist: "Drugi vagon & Dare Acoustic", desc: "snemanje za zgoščenko" },
            { artist: "Ljudski pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Laura Marn", desc: "snemanje demo pesmi" },
            { artist: "Vrtec Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Maja Mlakar", desc: "kantavtorica, snemanje za zgoščenko", status: "work" },
            { artist: "Ratko Zekić", desc: "violončelo, snemanje za zgoščenko", status: "work" },
            { artist: "Revije otorških and odraslih pevski skupin v občini Trebnje", desc: "snemanje na terenu" },
            { artist: "Dean Černec", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Bojan Rus", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Moški pevski zbor Tabor Cerknica", desc: "snemanje za zgoščenko" },
            { artist: "Ansambel Suha solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "AGB band", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Zidaniški kvintet", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Marjan Rogelj", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Mešani zbor upokojencev Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Trebanjski oktet", desc: "snemanje za zgoščenko" },
            { artist: "MPZ Mirna s filharmoniki RTV Slovenija", desc: "snemanje božičnega koncerta" },
            { artist: "Željko Rokvič z bandom", desc: "snemanje za zgoščenko" },
            { artist: "Sara Jagrič", desc: "snemanje demo pesmi" },
            { artist: "Vladimir", desc: "opera, snemanje demo pesmi" }
        ],
        audio: ["studiomars31/resta-immobile", "studiomars31/fly-me-the-moon"],
        videos: ["eQHiP9a6WD0", "b6XDgs8TN0A"]
    },
    "2018": {
        list: [
            { artist: "Jan Nograšek", desc: "snemanje avtorske pesmi" },
            { artist: "Jan Pance", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "Liljana Pance", desc: "snemanje opernih arij" },
            { artist: "Luka Žitnik trio", desc: "snemanje narodnozabavne skladbe" },
            { artist: "Filip Jagodič", desc: "snemanje za zgoščenko" },
            { artist: "Ah te orglice", desc: "snemanje srečanja orgličarjev v Mokronogu" },
            { artist: "Pevski zbor OŠ Veliki Gaber", desc: "snemanje šolske himne" },
            { artist: "Bojan Rus", desc: "snemanje avtorske pesmi" },
            { artist: "Revije otroških in odraslih pevskih skupin v občini Trebnje", desc: "snemanje na terenu" },
            { artist: "Skupina Soreline", desc: "snemanje koncerta" },
            { artist: "Storm Born Studio Italia", desc: "snemanje reklame za računalniško igro" },
            { artist: "Slavko Podboj", desc: "snemanje teksta za otvoritev muzeja Lojzeta Slaka" },
            { artist: "Ljudski pevci in godci Trebelno", desc: "snemanje za zgoščenko" },
            { artist: "Ljudski pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Mešani zbor upokojencev Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Metro Audio Video Studio", desc: "snemanje voiceover seminarjev za slovenska podjetja" },
            { artist: "Za Mirno z ljubeznijo", desc: "snemanje opernega koncerta (Irena Yebuah Tiran ...)" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta" },
            { artist: "Manca Pirc", desc: "snemanje demo posnetkov" }
        ],
        audio: ["andrej-mezan-studio-mars/killing-me-softly"],
        videos: ["e6mq6FEuepI"]
    },
    "2017": {
        list: [
            { artist: "Drugi vagon", desc: "Najdi" },
            { artist: "Laura in Ema", desc: "Kje je moje srce" },
            { artist: "Zagriški fantje", desc: "snemanje za zgoščenko" },
            { artist: "Alen Vogrinec vesel & Zidaniški kvintet", desc: "snemanje demo pesmi" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta" },
            { artist: "Ernest Klenovšek in Miran Klenovšek", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "18. mednarodni festival ustnih harmonik 2017", desc: "snemanje na terenu" },
            { artist: "Občočna revija odraslih pevskih zborov Mokronog - Trebelno", desc: "snemanje na terenu" },
            { artist: "Ana Vrtačnik", desc: "snemanje demo posnetkov", status: "work" },
            { artist: "Andrej Grandovec band in Rudarski oktet", desc: "snemanje dalmatinske pesmi", status: "work" },
            { artist: "Ansambel Suha Solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Glasbena skupina 5K", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Jerica Steklasa", desc: "snemanje koncerta" },
            { artist: "Ingenium Ensemble (Strmole kvartet)", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Maja Mlakar", desc: "kantavtorica, kitara, snemanje demo pesmi", status: "work" },
            { artist: "Sara Zajc", desc: "klasična kitara, snemanje za zgoščenko", status: "work" },
            { artist: "Darja Štamcar", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Hišni ansambel Avsenik", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Matej Pekolj", desc: "snemanje demo pesmi za harmoniko", status: "work" },
            { artist: "Željko Rokvič band", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje koncerta", status: "work" }
        ],
        audio: ["andrej-mezan-studio-mars/drugi-vagon-najdisi-9"],
        videos: ["ay1QWqvW4ok"]
    },
    "2016": {
        list: [
            { artist: "Darja Štamcar", desc: "Say Something" },
            { artist: "Občinski pihalni orkester Trebnje", desc: "Pokonci, Trebanjci!" },
            { artist: "Občinski pihalni orkester Trebnje", desc: "Think" },
            { artist: "Timo Grandovec & Sinovi cvička", desc: "Gremo spet v vinsko klet" },
            { artist: "Vizija Računovodstvo", desc: "Reklama" },
            { artist: "Luka Groboljšek & Zagorski oktet", desc: "Moj zeleni raj" },
            { artist: "Fantje iz Praprotna & družba", desc: "Mojca Dolenc - 50 let" },
            { artist: "Ansambel Suha solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Studio Virc", desc: "snemanje za telefonsko tajnico" },
            { artist: "Miran Černec", desc: "kantavtor, demo posnetki", status: "work" },
            { artist: "Trebanjski oktet", desc: "snemanje koncerta ob 35 letnici" },
            { artist: "MePZ Notranjska", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Oriflame", desc: "snemanje za podjetje Oriflame kozmetika d.o.o." },
            { artist: "Ansambel M-Tom Mirna", desc: "snemanje posnetka za promocijo podjetja M-Tom" },
            { artist: "Danilo Lukan", desc: "demo posnetki" },
            { artist: "OŠ Šentrupert", desc: "snemanje za himno" },
            { artist: "Ansambel Mladi Dolenjci", desc: "snemanje za reklamo" },
            { artist: "AGB in prijatelji", desc: "snemanje dalmatinske pesmi" },
            { artist: "Tinkara Lazar", desc: "snemanje demo pesmi", status: "work" },
            { artist: "Matevž Mikeln", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Tilen Zakrajšek", desc: "bobni, snemanje demo posnetkov", status: "work" }
        ],
        audio: [
            "andrej-mezan-studio-mars/darja-stamcar-say-something-6",
            "andrej-mezan-studio-mars/pihalni-orkester-trebnje-pokonci-trebanjci-32",
            "andrej-mezan-studio-mars/pihalni-orkester-trebnje-think-33",
            "andrej-mezan-studio-mars/luka-groboljsek-moj-zeleni-raj-23",
            "podari-pesem/gremo-spet-v-vinsko-klet-timo-grandovec-sinovi-cvicka-4",
            "podari-pesem/vizija-racunovodstvo-reklama-za-podjetje-16",
            "podari-pesem/mojca-dolenc-50-let-fantje-iz-praprotna-druzba-14"
        ],
        videos: []
    },
    "2015": {
        list: [
            { artist: "Lucija Tacer", desc: "Up In The Sun" },
            { artist: "Luka Groboljšek", desc: "Valček za ukulele" },
            { artist: "Ansambel Vrisk", desc: "Regratova lučka" },
            { artist: "Matevž Mikeln", desc: "Zadnja noč" },
            { artist: "Združena moška pevska zbora Fran Venturini ...", desc: "Vstala primorska" },
            { artist: "Trio adijo", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Željko Mevželj", desc: "demo posnetki" },
            { artist: "Pihalni orkester Trebnje", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Za Mirno z ljubeznijo", desc: "snemanje koncerta in izdelava zgoščenk" },
            { artist: "Ratko", desc: "violončelo, demo posnetki" },
            { artist: "Pevski zbor slepih in slabovidnih Novo Mesto", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "DMT Hardcore", desc: "mastering" },
            { artist: "Dean Černec", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "MePZ Matija Tomc Mirna", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Srečanje ZDUS Cankarjev dom", desc: "snemanje preireditve in izdaja zgoščenke", status: "work" },
            { artist: "Sara Zajc", desc: "akustična kitara, demo posnetki", status: "work" },
            { artist: "Žan ograjšek", desc: "kantavtor, demo posnetki", status: "work" },
            { artist: "Koncert oktet Lipa", desc: "snemanje koncerta", status: "work" },
            { artist: "Vokalna skupina Črta", desc: "demo posnetki", status: "work" },
            { artist: "Tinkara Lazar", desc: "demo posnetki", status: "work" },
            { artist: "Studio Virc", desc: "snemanje telefonske tajnice za T2" },
            { artist: "Metro Audio VIdeo", desc: "snemanje slovenske različice za iROBOT" }
        ],
        audio: ["andrej-mezan-studio-mars/lucija-tacer-up-in-the-sun-22", "andrej-mezan-studio-mars/luka-groboljsek-valcek-za-ukulele-24", "andrej-mezan-studio-mars/regratova-lucka-1", "andrej-mezan-studio-mars/matevz-mikelj-zadnja-noc-26"],
        videos: ["BzPaqmgVTLE", "DnTieftXy3M"]
    },
    "2014": {
        list: [
            { artist: "Jamm", desc: "At Last" },
            { artist: "Primož Bulc", desc: "Ni še čas za umret" },
            { artist: "Ansambel Kolibri", desc: "Naša mati" },
            { artist: "MePZ Tabor Cerknica", desc: "Kaj tam se v vinogradu bliska" },
            { artist: "Kvartet Slavček", desc: "Po gorah grmi" },
            { artist: "No Name Band", desc: "Love Hurts" },
            { artist: "Grajski oktet", desc: "Zelena dežela" },
            { artist: "Skupina JAMM", desc: "snemanje demo posnetkov" },
            { artist: "Ansambel Suha solza", desc: "snemanje za zgoščenko", status: "work" },
            { artist: "Studio Virc", desc: "snemanje za video produkcijo" },
            { artist: "Skupina Dežur", desc: "snemanje pesmi za slovensko popevko 2014" },
            { artist: "Tinkara Lazar", desc: "snemanje demo posnetkov" },
            { artist: "Godalni orkester glasbene šole Trebnje z Bernardo Fink", desc: "koncert" },
            { artist: "MePZ DU Mirna", desc: "snemanje koncerta ob 15. letnici" },
            { artist: "Ansambel \"Tom Mirna\"", desc: "snemanje demo posnetkov" },
            { artist: "Zveza društva upokojencev Slovenije", desc: "snemanje srečanja, Cankarjev dom" },
            { artist: "Matej Glivar", desc: "demo posnetki" },
            { artist: "Krishna", desc: "akustična kitara, demo posnetki" },
            { artist: "Vaški pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Ernest Klenovšek", desc: "harmonika, snemanje za zgoščenko" },
            { artist: "Matjaž Zupančič", desc: "snemanje klavirja, demo posnetki" }
        ],
        audio: ["andrej-mezan-studio-mars/jamm-at-last-16", "andrej-mezan-studio-mars/primoz-bulc-ni-se-cas-za-umret-34", "andrej-mezan-studio-mars/ansambel-kolibri-nasa-mati-3", "andrej-mezan-studio-mars/mepz-tabor-cerknica-kaj-tam-se-v-vinogradu-bliska-27", "andrej-mezan-studio-mars/kvartet-slavcek-po-gorah-grmi-18", "andrej-mezan-studio-mars/no-name-band-love-hurts-28", "andrej-mezan-studio-mars/grajski-oktet-zelena-dezela-13"],
        videos: ["w5HNDtBublI", "qyegtMrtJKI"]
    },
    "2013": {
        list: [
            { artist: "Zlobko Big Band in Revijski orkester Trebnje", desc: "Himna mesta Trebnje" },
            { artist: "Ivo Carič", desc: "Žuborenje" },
            { artist: "Karmen Virc (Govornica)", desc: "Navigacija za Google Maps" },
            { artist: "Tinkara Lazar", desc: "For a Thousand Years" },
            { artist: "DeŽur", desc: "Morje čaka" },
            { artist: "Tomaž Plahutnik in Mojca Dolenc", desc: "Sijaj, sijaj sončece" },
            { artist: "Ansambel Dolinarji", desc: "Naj ta valček najlepše zazveni" },
            { artist: "Irena Tratnik in Blaž Jurjevčič", desc: "Perfidia" },
            { artist: "Damjan Plevnik", desc: "Da te mogu pismom zvati" },
            { artist: "Julija Omahen", desc: "You Raise Me Up" },
            { artist: "Ansambel Suha solza", desc: "material za zgoščenko", status: "work" },
            { artist: "Daša Savić", desc: "violina, demo posnetki" },
            { artist: "Sistem ena d.o.o", desc: "snemanje za telefonsko tajnico" },
            { artist: "TMC", desc: "rap, demo posnetki" },
            { artist: "Glasbena šola Studio Kreator", desc: "za zgoščenko ljudskih pesmi" },
            { artist: "Glasbena šola Marolt", desc: "snemanje za promocijsko pesem" },
            { artist: "Ana Zlobko", desc: "violončelo, koncert" },
            { artist: "MePZ društva upokojencev Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Žan Ograjšek", desc: "kantavtor, demo posnetki" },
            { artist: "Mladi godci", desc: "narodno-zabavna, demo posnetki" },
            { artist: "Sandra Erpe", desc: "snemanje avtorskega singla" },
            { artist: "Dejan Černec", desc: "kantavtor (s triom Blaž Jurjevčič, Vlado Pirc, Bogdan Turnšek)" },
            { artist: "Vokalna skupina Rozalije", desc: "demo posnetki" },
            { artist: "MePZ društva upokojencev Mirna", desc: "snemanje in izdaja koncerta Cankarjev dom" },
            { artist: "Klavdija Zakrajšek", desc: "snemanje demo posnetka" },
            { artist: "Srečanje oktetov Dolenjske in Bele krajine 2013", desc: "snemanje koncerta" },
            { artist: "KUD Matija Tomc Mirna", desc: "snemanje za zgoščenko" }
        ],
        audio: [
            "andrej-mezan-studio-mars/zlobko-big-band-himna-mesta-trebnje-42",
            "andrej-mezan-studio-mars/ivo-caric-zuborenje-15",
            "andrej-mezan-studio-mars/karmen-virc-navigacija-17",
            "andrej-mezan-studio-mars/dezur-morje-caka-7",
            "andrej-mezan-studio-mars/irena-tratnik-blaz-jurjevcic-perfidia-14",
            "andrej-mezan-studio-mars/damjan-plevnik-da-te-mogu-pismom-zvati-5",
            "podari-pesem/for-a-thousand-years-tinkara-lazar-7",
            "podari-pesem/dolinarji-naj-ta-valcek-najlepse-zazveni-5"
        ],
        videos: ["RmIp0HEUw5k"]
    },
    "2012": {
        list: [
            { artist: "Sandbarry", desc: "Premlada sva bila" },
            { artist: "Tinkara Lazar", desc: "Make You Feel My Love" },
            { artist: "Eva Virc", desc: "Od časa do časa" },
            { artist: "Eva Virc", desc: "En like" },
            { artist: "Ansambel Ponos", desc: "Na večne dni" },
            { artist: "Ansambel Večerni zvon", desc: "Ne zapravite mi žuljev" },
            { artist: "Ženski zbor Zimzelen Mirna", desc: "snemanje za zgoščenko" },
            { artist: "Asnambel Vrisk", desc: "snemanje za videospot" },
            { artist: "Glasbena šola Marolt", desc: "snemanje mladih harmonikašev" },
            { artist: "OŠ Trebnje", desc: "snemanje pevskih skupin za zgoščenko" },
            { artist: "Ansambel Ravbar", desc: "demo posnetki" },
            { artist: "Ansambel Posluh", desc: "demo posnetki" },
            { artist: "Pihalni orkester Trebnje", desc: "snemanje koncerta filmske glasbe" },
            { artist: "Dean Černec", desc: "kantavtor, demo posnetki" },
            { artist: "Skupina Vaški pevci Šentrupert", desc: "snemanje za zgoščenko" },
            { artist: "Glasbena šola Studio Kreator", desc: "snemanje materiala za učenje na daljavo" },
            { artist: "Tjaša Boršnak", desc: "demo posnetek" },
            { artist: "Studio Virc d.o.o", desc: "snemanje zvočne podlage za video" },
            { artist: "Ernest Klenovšek", desc: "harmonika, snemanje za zgoščenko" },
            { artist: "Ansambel Glivar", desc: "demo posnetki" },
            { artist: "MEPZ Mirna in orkester Slovenske filharmonije", desc: "koncert" }
        ],
        audio: [
            "andrej-mezan-studio-mars/sandbarry-premlada-sva-bila-35",
            "andrej-mezan-studio-mars/eva-virc-en-like-10",
            "podari-pesem/eva-virc-od-casa-do-casa-6",
            "podari-pesem/na-vecne-dni-ansambel-ponos-2",
            "podari-pesem/ne-zapravite-mi-zuljev-ansambel-vecerni-zvon-15",
            "podari-pesem/make-you-fell-my-love-tinkara-lazar-13"
        ],
        videos: ["Tyhso6gqHfo", "76fTJoDOtJQ"]
    },
    "2011": {
        list: [
            { artist: "HD Lab", desc: "Tell The Truth" },
            { artist: "Pihalni orkester Botriček", desc: "Aljoša, dvigni glaž!" },
            { artist: "MePZ Anton Foerster in solist Marcos Fink", desc: "Mati domovina" },
            { artist: "Klavdija Zakrajšek", desc: "The Climb (Cover)" },
            { artist: "Katja Stropnik", desc: "Turning Tables (Cover)" },
            { artist: "Kvartet Sever", desc: "Šentjurska" },
            { artist: "Anica Blažič", desc: "snemanje za oddajo Slovenija ima talent 2011" },
            { artist: "Obrtniški pevski zbor Notranjska", desc: "snemanje materiala za zgoščenko" },
            { artist: "Slavko Podboj", desc: "snemanje radijskih reklam" },
            { artist: "Biizy", desc: "rap, demo posnetki" },
            { artist: "Klapa Kres", desc: "posnetek za tekmovanje dalmatinskih klap Korčula 2011", status: "work" },
            { artist: "Špela Smuk", desc: "snemanje reklam za županske volitve" },
            { artist: "Oto Pestner in Zidaniški kvintet", desc: "projekt avtorja A. Krkoviča" },
            { artist: "Vrtec Trebnje", desc: "demo posnetki" },
            { artist: "Marko Kuzhnik", desc: "rap, demo posnetki" },
            { artist: "Ansambel Suha solza", desc: "narodno-zabavna, demo posnetki" }
        ],
        audio: [
            "podari-pesem/sentjurska-kvartet-sever-12",
            "podari-pesem/hdlab-tell-the-truth-8",
            "podari-pesem/aljosa-dvigni-glaz-pihalni-orkester-botricek-1",
            "podari-pesem/anton-foerster-in-marcos-fink-domovina-je-mati-3",
            "podari-pesem/klavdija-zakrajsek-the-climb-11"
        ],
        videos: ["d2sRatjFLig"]
    },
    "2010": {
        list: [
            { artist: "Andrej Mežan", desc: "In The Sweet" },
            { artist: "Trebanjski oktet", desc: "Angelček" },
            { artist: "The Call Boys", desc: "Dolenjska je moja mati" },
            { artist: "Godalni trio Viva", desc: "Nessun Dorma" },
            { artist: "Mešani pevski zbor Kres Čatež", desc: "material za zgoščenko" },
            { artist: "Oktet Lipa", desc: "snemanje koncerta ob 20 letnici" },
            { artist: "Albin Slabe, godec ljudskih viž", desc: "material za zgočenko" },
            { artist: "Folklorna skupina Nasmeh", desc: "material za zgoščenko" },
            { artist: "Glasbena šola Studio Kreator", desc: "material za gl. šolo na daljavo" }
        ],
        audio: ["andrej-mezan-studio-mars/andrej-mezan-in-the-sweet-2", "andrej-mezan-studio-mars/trebanjski-oktet-angelcek-38", "andrej-mezan-studio-mars/the-call-boys-dolenjska-je-moja-mati-37", "andrej-mezan-studio-mars/godalni-trio-viva-nessun-dorma-12"],
        videos: []
    },
    "2009": {
        list: [
            { artist: "LSQ", desc: "Back In The Days" },
            { artist: "Schlager kvintet", desc: "Na fax" },
            { artist: "Kvartet Trenotek", desc: "Snežinke bele zvezdice" },
            { artist: "Zidaniški kvintet", desc: "Samski stan" },
            { artist: "Zidaniški kvintet", desc: "Tako lepo (prir. It's Not Unusual)" },
            { artist: "Gianni Rijavec in Zidaniški kvintet", desc: "V meni bije slovensko srce" },
            { artist: "Ansambel Vrisk", desc: "Recesija" },
            { artist: "Marko Kuzhnik", desc: "rap, demo posnetki" },
            { artist: "Triglavski muzikanti", desc: "material za zgoščenko" },
            { artist: "Otroški zborček VVZ Trebnje", desc: "demo posnetki" },
            { artist: "Glasbena skupina Stopinje", desc: "demo posnetki" },
            { artist: "MePZ Danica", desc: "material za zgoščenko" },
            { artist: "Kvartet tub, člani orkestra Slovenske vojske", desc: "demo posnetki" },
            { artist: "Vokalna skupina Ragle", desc: "material za zgoščenko" }
        ],
        audio: ["andrej-mezan-studio-mars/lsq-back-in-the-days-20", "andrej-mezan-studio-mars/schlager-kvintet-na-fax-36", "andrej-mezan-studio-mars/kvartet-trenotek-snezinke-bele-zvezdice-19", "andrej-mezan-studio-mars/zidaniski-kvintet-samski-stan-40", "andrej-mezan-studio-mars/zidaniski-kvintet-tako-lepo-41", "andrej-mezan-studio-mars/gianni-rijavec-zidaniski-kvintet-v-meni-bije-slovensko-srce-11", "andrej-mezan-studio-mars/ansambel-vrisk-recesija-4"],
        videos: []
    },
    "2008": {
        list: [
            { artist: "Zlobko Big Band z Nušo Derendo in Rajkom Vavpetičem", desc: "Le verjemi" },
            { artist: "Zlobko Big Band z Nušo Derendo in Rajkom Vavpetičem", desc: "Ne čakaj na maj" },
            { artist: "Oto Pestner", desc: "Blind Barnabus" },
            { artist: "Matej Krajnc", desc: "Stvari" },
            { artist: "Zidaniški kvintet", desc: "Polka za majolko" },
            { artist: "D’neeb", desc: "Slovo" },
            { artist: "Stil Quartet", desc: "demo posnetki, producent Oto Pestner" },
            { artist: "Marjetka Hribernik", desc: "violončelo, demo posnetki, producent Oto Pestner" },
            { artist: "Trebanjski oktet", desc: "demo posnetki" }
        ],
        audio: [
            "andrej-mezan-studio-mars/nusa-derenda-rajko-vavpetic-le-verjemi-29",
            "andrej-mezan-studio-mars/nusa-derenda-rajko-vavpetic-ne-cakaj-na-maj-30",
            "andrej-mezan-studio-mars/oto-pestner-blind-barnabus-31",
            "andrej-mezan-studio-mars/matej-krajnc-stvari-25",
            "andrej-mezan-studio-mars/zidaniski-kvintet-polka-za-majolko-39",
            "andrej-mezan-studio-mars/dneeb-slovo-8"
        ],
        videos: []
    }
};
